"""Fix typos in models and update schema

Revision ID: 4b651582b354
Revises: b50284727e57
Create Date: 2024-10-16 12:30:22.372766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b651582b354'
down_revision = 'b50284727e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_group_invitations_invited_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_group_invitations_invited_user_id_users'), 'users', ['invited_user_id'], ['id'])
        batch_op.drop_column('invited_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_user', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_group_invitations_invited_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_group_invitations_invited_user_users', 'users', ['invited_user'], ['id'])
        batch_op.drop_column('invited_user_id')

    # ### end Alembic commands ###
